#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input())
    
    maximum = 0
    consecutive = 0

    while n > 0:
        if n % 2 == 1:
            consecutive = consecutive + 1
            maximum = max(consecutive, maximum)
        else:
            consecutive = 0 
        n = n // 2
    print(maximum)
